#! /usr/bin/env python
# -*- mode: Python -*-

import atexit, os, readline

fn = os.environ["HOME"] + "/.python_history"

# hack to ensure ~/.python_history exists
f = open (fn, "a")
f.close ()

histfile = os.path.expanduser (fn)
readline.read_history_file (histfile)
atexit.register (readline.write_history_file, histfile)
